### ISSUE TITLE
Q: Project status?

### ISSUE THREAD

**Issue by westurner** [rkern/grin#8]
What is the status of this project?

Is there any chance that any of the Python3 support PRs will be merged and released to pypi?
If not -- and I'm not volunteering -- could a different maintainer merge a PR and release to pypi?

@rkern Should I just install grin3 instead? (e.g. with ``pipsi install grin3``)
https://pypi.org/project/grin3/
https://bitbucket.org/rsalmaso/grin3/commits/all

**Comment by rkern** [comment]
https://github.com/matthew-brett/grin
